title: Channel Chirp
description: Green-cheeked and Big Beaked
url: https://channelchirp.com
baseurl: ""
timezone: Australia/Sydney

# The blog structure
permalink: /:title/

# Pagination for the blog (adventures)
paginate: 5
paginate_path: "/adventures/page:num/"


# Not needed to send to the internet or something but optional to not do.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  
# The plugin section!
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Archives drop-down box!
jekyll-archives:
  enabled:
    - month
  layout: default
  permalinks:
    month: '/:year/:month/'